import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      
       
       
        <div className={styles.hero}>
           <h2 className={styles.holy}>THE WORD</h2>
                <h1 className={styles.bible}>
                    <a href="https://the-holy-bible.vercel.app/" target="_blank">OF GOD</a>
                </h1>
        
        <h1 className={styles.title}>
          THE REVELATION
        </h1>
         <div  className={styles.image}>
       <Image 
                                src="/blue_letter_bible.jpeg"
                                alt="Jesus teaching"
                                height={900}
                                width={2000}
                                priority
                              />
          </div>
                      <div className={styles.nav}>           
      <a href="https://colossians.vercel.app/">
             <Image 
                                src="/chevron-left.svg"
                                alt="left"
                                 height={25}
                                width={25}
                                priority
                              />
       </a>

         <a href="#PayPalButton">
            <Image 
                                src="/chevron-down.svg"
                                alt="down"
                                 height={25}
                                width={25}
                                priority
                              />
           
        </a> 
         <a href="https://second-thessalonians.vercel.app/">
           <Image 
                                src="/chevron-right.svg"
                                alt="right"
                                 height={25}
                                width={25}
                                priority
                              />
           
        </a> 
         
               </div>
                <div className={styles.iframe}>
                      <iframe width="100%" height="315" src="https://www.youtube.com/embed/5nvVVcYD-0w" title="YouTube video player" frameborder="1" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
                </div>        
      <div className={styles.grid}>
          <div className={styles.card}>
            <h2 className={styles.chapter}>The Revelation Chpt I</h2>
            <p>
              The revelation from Jesus Christ, which God gave him to show his servants what must soon take place. He made it known by sending his angel to his servant John, 2 who testifies to everything he saw—that is, the word of God and the testimony of Jesus Christ. 3 
Blessed is the one who reads aloud the words of this prophecy, and blessed are those who hear it and take to heart what is written in it, because the time is near.

Greetings and Doxology
4 John,

To the seven churches in the province of Asia:

Grace and peace to you from him who is, and who was, and who is to come, and from the seven spirits[a] before his throne, 5 and from Jesus Christ, who is the faithful witness, the firstborn from the dead, and the ruler of the kings of the earth.

To him who loves us and has freed us from our sins by his blood, 6 and has made us to be a kingdom and priests to serve his God and Father—to him be glory and power for ever and ever! Amen.

7 “Look, he is coming with the clouds,”[b]
    and “every eye will see him,
even those who pierced him”;
    and all peoples on earth “will mourn because of him.”[c]
So shall it be! Amen.

8 “I am the Alpha and the Omega,” says the Lord God, “who is, and who was, and who is to come, the Almighty.”

John’s Vision of Christ
9 I, John, your brother and companion in the suffering and kingdom and patient endurance that are ours in Jesus, was on the island of Patmos because of the word of God and the testimony of Jesus. 10 On the Lord’s Day I was in the Spirit, and I heard behind me a loud voice like a trumpet, 11 which said: “Write on a scroll what you see and send it to the seven churches: to Ephesus, Smyrna, Pergamum, Thyatira, Sardis, Philadelphia and Laodicea.”

12 I turned around to see the voice that was speaking to me. And when I turned I saw seven golden lampstands, 13 and among the lampstands was someone like a son of man,[d] dressed in a robe reaching down to his feet and with a golden sash around his chest. 14 The hair on his head was white like wool, as white as snow, and his eyes were like blazing fire. 15 His feet were like bronze glowing in a furnace, and his voice was like the sound of rushing waters. 16 In his right hand he held seven stars, and coming out of his mouth was a sharp, double-edged sword. His face was like the sun shining in all its brilliance.

17 When I saw him, I fell at his feet as though dead. Then he placed his right hand on me and said: “Do not be afraid. I am the First and the Last. 18 I am the Living One; I was dead, and now look, I am alive for ever and ever! And I hold the keys of death and Hades.

19 “Write, therefore, what you have seen, what is now and what will take place later. 20 The mystery of the seven stars that you saw in my right hand and of the seven golden lampstands is this: The seven stars are the angels[e] of the seven churches, and the seven lampstands are the seven churches.
              </p>
              </div>

          <div className={styles.card}>
           <h2 className={styles.chapter}>The Revelation Chpt II</h2>
            <p>To the Church in Ephesus
2 “To the angel[a] of the church in Ephesus write:

These are the words of him who holds the seven stars in his right hand and walks among the seven golden lampstands. 2 I know your deeds, your hard work and your perseverance. I know that you cannot tolerate wicked people, that you have tested those who claim to be apostles but are not, and have found them false. 3 You have persevered and have endured hardships for my name, and have not grown weary.

4 Yet I hold this against you: You have forsaken the love you had at first. 5 Consider how far you have fallen! Repent and do the things you did at first. If you do not repent, I will come to you and remove your lampstand from its place. 6 But you have this in your favor: You hate the practices of the Nicolaitans, which I also hate.

7 Whoever has ears, let them hear what the Spirit says to the churches. To the one who is victorious, I will give the right to eat from the tree of life, which is in the paradise of God.

To the Church in Smyrna
8 “To the angel of the church in Smyrna write:

These are the words of him who is the First and the Last, who died and came to life again. 9 I know your afflictions and your poverty—yet you are rich! I know about the slander of those who say they are Jews and are not, but are a synagogue of Satan. 10 Do not be afraid of what you are about to suffer. I tell you, the devil will put some of you in prison to test you, and you will suffer persecution for ten days. Be faithful, even to the point of death, and I will give you life as your victor’s crown.

11 Whoever has ears, let them hear what the Spirit says to the churches. The one who is victorious will not be hurt at all by the second death.

To the Church in Pergamum
12 “To the angel of the church in Pergamum write:

These are the words of him who has the sharp, double-edged sword. 13 I know where you live—where Satan has his throne. Yet you remain true to my name. You did not renounce your faith in me, not even in the days of Antipas, my faithful witness, who was put to death in your city—where Satan lives.

14 Nevertheless, I have a few things against you: There are some among you who hold to the teaching of Balaam, who taught Balak to entice the Israelites to sin so that they ate food sacrificed to idols and committed sexual immorality. 15 Likewise, you also have those who hold to the teaching of the Nicolaitans. 16 Repent therefore! Otherwise, I will soon come to you and will fight against them with the sword of my mouth.

17 Whoever has ears, let them hear what the Spirit says to the churches. To the one who is victorious, I will give some of the hidden manna. I will also give that person a white stone with a new name written on it, known only to the one who receives it.

To the Church in Thyatira
18 “To the angel of the church in Thyatira write:

These are the words of the Son of God, whose eyes are like blazing fire and whose feet are like burnished bronze. 19 I know your deeds, your love and faith, your service and perseverance, and that you are now doing more than you did at first.

20 Nevertheless, I have this against you: You tolerate that woman Jezebel, who calls herself a prophet. By her teaching she misleads my servants into sexual immorality and the eating of food sacrificed to idols. 21 I have given her time to repent of her immorality, but she is unwilling. 22 So I will cast her on a bed of suffering, and I will make those who commit adultery with her suffer intensely, unless they repent of her ways. 23 I will strike her children dead. Then all the churches will know that I am he who searches hearts and minds, and I will repay each of you according to your deeds.

24 Now I say to the rest of you in Thyatira, to you who do not hold to her teaching and have not learned Satan’s so-called deep secrets, ‘I will not impose any other burden on you, 25 except to hold on to what you have until I come.’

26 To the one who is victorious and does my will to the end, I will give authority over the nations— 27 that one ‘will rule them with an iron scepter and will dash them to pieces like pottery’[b]—just as I have received authority from my Father. 28 I will also give that one the morning star. 29 Whoever has ears, let them hear what the Spirit says to the churches.</p>
          </div>

          <div
            className={styles.card}
          >
           <h2 className={styles.chapter}>The Revelation Chpt III</h2>
            <p>
            To the Church in Sardis
3 “To the angel[a] of the church in Sardis write:

These are the words of him who holds the seven spirits[b] of God and the seven stars. I know your deeds; you have a reputation of being alive, but you are dead. 2 Wake up! Strengthen what remains and is about to die, for I have found your deeds unfinished in the sight of my God. 3 Remember, therefore, what you have received and heard; hold it fast, and repent. But if you do not wake up, I will come like a thief, and you will not know at what time I will come to you.

4 Yet you have a few people in Sardis who have not soiled their clothes. They will walk with me, dressed in white, for they are worthy. 5 The one who is victorious will, like them, be dressed in white. I will never blot out the name of that person from the book of life, but will acknowledge that name before my Father and his angels. 6 Whoever has ears, let them hear what the Spirit says to the churches.

To the Church in Philadelphia
7 “To the angel of the church in Philadelphia write:

These are the words of him who is holy and true, who holds the key of David. What he opens no one can shut, and what he shuts no one can open. 8 I know your deeds. See, I have placed before you an open door that no one can shut. I know that you have little strength, yet you have kept my word and have not denied my name. 9 I will make those who are of the synagogue of Satan, who claim to be Jews though they are not, but are liars—I will make them come and fall down at your feet and acknowledge that I have loved you. 10 Since you have kept my command to endure patiently, I will also keep you from the hour of trial that is going to come on the whole world to test the inhabitants of the earth.

11 I am coming soon. Hold on to what you have, so that no one will take your crown. 12 The one who is victorious I will make a pillar in the temple of my God. Never again will they leave it. I will write on them the name of my God and the name of the city of my God, the new Jerusalem, which is coming down out of heaven from my God; and I will also write on them my new name. 13 Whoever has ears, let them hear what the Spirit says to the churches.

To the Church in Laodicea
14 “To the angel of the church in Laodicea write:

These are the words of the Amen, the faithful and true witness, the ruler of God’s creation. 15 I know your deeds, that you are neither cold nor hot. I wish you were either one or the other! 16 So, because you are lukewarm—neither hot nor cold—I am about to spit you out of my mouth. 17 You say, ‘I am rich; I have acquired wealth and do not need a thing.’ But you do not realize that you are wretched, pitiful, poor, blind and naked. 18 I counsel you to buy from me gold refined in the fire, so you can become rich; and white clothes to wear, so you can cover your shameful nakedness; and salve to put on your eyes, so you can see.

19 Those whom I love I rebuke and discipline. So be earnest and repent. 20 Here I am! I stand at the door and knock. If anyone hears my voice and opens the door, I will come in and eat with that person, and they with me.

21 To the one who is victorious, I will give the right to sit with me on my throne, just as I was victorious and sat down with my Father on his throne. 22 Whoever has ears, let them hear what the Spirit says to the churches.”
            </p>
          </div>
<div className={styles.card}>

<h2 className={styles.chapter}>The Revelation Chpt IV</h2>
<p>
The Throne in Heaven
4 After this I looked, and there before me was a door standing open in heaven. And the voice I had first heard speaking to me like a trumpet said, “Come up here, and I will show you what must take place after this.” 2 At once I was in the Spirit, and there before me was a throne in heaven with someone sitting on it. 3 And the one who sat there had the appearance of jasper and ruby. A rainbow that shone like an emerald encircled the throne. 4 Surrounding the throne were twenty-four other thrones, and seated on them were twenty-four elders. They were dressed in white and had crowns of gold on their heads. 5 From the throne came flashes of lightning, rumblings and peals of thunder. In front of the throne, seven lamps were blazing. These are the seven spirits[a] of God. 6 Also in front of the throne there was what looked like a sea of glass, clear as crystal.

In the center, around the throne, were four living creatures, and they were covered with eyes, in front and in back. 7 The first living creature was like a lion, the second was like an ox, the third had a face like a man, the fourth was like a flying eagle. 8 Each of the four living creatures had six wings and was covered with eyes all around, even under its wings. Day and night they never stop saying:

“‘Holy, holy, holy

is the Lord God Almighty,’[b]

who was, and is, and is to come.”

9 Whenever the living creatures give glory, honor and thanks to him who sits on the throne and who lives for ever and ever, 10 the twenty-four elders fall down before him who sits on the throne and worship him who lives for ever and ever. They lay their crowns before the throne and say:

11 “You are worthy, our Lord and God,
    to receive glory and honor and power,
for you created all things,
    and by your will they were created
    and have their being.”
</p>
</div>

                                      <div className={styles.card}>

                                      <h2 className={styles.chapter}>The Revelation Chpt V</h2>
                                      <p>

                                      The Scroll and the Lamb
                                      5 Then I saw in the right hand of him who sat on the throne a scroll with writing on both sides and sealed with seven seals. 2 And I saw a mighty angel proclaiming in a loud voice, “Who is worthy to break the seals and open the scroll?” 3 But no one in heaven or on earth or under the earth could open the scroll or even look inside it. 4 I wept and wept because no one was found who was worthy to open the scroll or look inside. 5 Then one of the elders said to me, “Do not weep! See, the Lion of the tribe of Judah, the Root of David, has triumphed. He is able to open the scroll and its seven seals.”

                                      6 Then I saw a Lamb, looking as if it had been slain, standing at the center of the throne, encircled by the four living creatures and the elders. The Lamb had seven horns and seven eyes, which are the seven spirits[a] of God sent out into all the earth. 7 He went and took the scroll from the right hand of him who sat on the throne. 8 And when he had taken it, the four living creatures and the twenty-four elders fell down before the Lamb. Each one had a harp and they were holding golden bowls full of incense, which are the prayers of God’s people. 9 And they sang a new song, saying:

                                      “You are worthy to take the scroll
                                          and to open its seals,
                                      because you were slain,
                                          and with your blood you purchased for God
                                          persons from every tribe and language and people and nation.
                                      10 You have made them to be a kingdom and priests to serve our God,
                                          and they will reign[b] on the earth.”

                                      11 Then I looked and heard the voice of many angels, numbering thousands upon thousands, and ten thousand times ten thousand. They encircled the throne and the living creatures and the elders. 12 In a loud voice they were saying:

                                      “Worthy is the Lamb, who was slain,
                                          to receive power and wealth and wisdom and strength
                                          and honor and glory and praise!”

                                      13 Then I heard every creature in heaven and on earth and under the earth and on the sea, and all that is in them, saying:

                                      “To him who sits on the throne and to the Lamb
                                          be praise and honor and glory and power,
                                      for ever and ever!”

                                      14 The four living creatures said, “Amen,” and the elders fell down and worshiped.     
                                        </p>
                                      </div>
  
                                        <div className={styles.card}>

                                        <h2 className={styles.chapter}>The Revelation Chpt VI</h2>
                                        <p>
                                          The Seals
                              6 I watched as the Lamb opened the first of the seven seals. Then I heard one of the four living creatures say in a voice like thunder, “Come!” 2 I looked, and there before me was a white horse! Its rider held a bow, and he was given a crown, and he rode out as a conqueror bent on conquest.

                              3 When the Lamb opened the second seal, I heard the second living creature say, “Come!” 4 Then another horse came out, a fiery red one. Its rider was given power to take peace from the earth and to make people kill each other. To him was given a large sword.

                              5 When the Lamb opened the third seal, I heard the third living creature say, “Come!” I looked, and there before me was a black horse! Its rider was holding a pair of scales in his hand. 6 Then I heard what sounded like a voice among the four living creatures, saying, “Two pounds[a] of wheat for a day’s wages,[b] and six pounds[c] of barley for a day’s wages,[d] and do not damage the oil and the wine!”

                              7 When the Lamb opened the fourth seal, I heard the voice of the fourth living creature say, “Come!” 8 I looked, and there before me was a pale horse! Its rider was named Death, and Hades was following close behind him. They were given power over a fourth of the earth to kill by sword, famine and plague, and by the wild beasts of the earth.

                              9 When he opened the fifth seal, I saw under the altar the souls of those who had been slain because of the word of God and the testimony they had maintained. 10 They called out in a loud voice, “How long, Sovereign Lord, holy and true, until you judge the inhabitants of the earth and avenge our blood?” 11 Then each of them was given a white robe, and they were told to wait a little longer, until the full number of their fellow servants, their brothers and sisters,[e] were killed just as they had been.

                              12 I watched as he opened the sixth seal. There was a great earthquake. The sun turned black like sackcloth made of goat hair, the whole moon turned blood red, 13 and the stars in the sky fell to earth, as figs drop from a fig tree when shaken by a strong wind. 14 The heavens receded like a scroll being rolled up, and every mountain and island was removed from its place.

                              15 Then the kings of the earth, the princes, the generals, the rich, the mighty, and everyone else, both slave and free, hid in caves and among the rocks of the mountains. 16 They called to the mountains and the rocks, “Fall on us and hide us[f] from the face of him who sits on the throne and from the wrath of the Lamb! 17 For the great day of their[g] wrath has come, and who can withstand it?”
                                        </p>
                                        </div>

                              <div className={styles.card}>

                                        <h2 className={styles.chapter}>The Revelation Chpt VI</h2>
                                        <p>
                                                                                  144,000 Sealed
                                          7 After this I saw four angels standing at the four corners of the earth, holding back the four winds of the earth to prevent any wind from blowing on the land or on the sea or on any tree. 2 Then I saw another angel coming up from the east, having the seal of the living God. He called out in a loud voice to the four angels who had been given power to harm the land and the sea: 3 “Do not harm the land or the sea or the trees until we put a seal on the foreheads of the servants of our God.” 4 Then I heard the number of those who were sealed: 144,000 from all the tribes of Israel.

                                          5 From the tribe of Judah 12,000 were sealed,

                                          from the tribe of Reuben 12,000,

                                          from the tribe of Gad 12,000,

                                          6 from the tribe of Asher 12,000,

                                          from the tribe of Naphtali 12,000,

                                          from the tribe of Manasseh 12,000,

                                          7 from the tribe of Simeon 12,000,

                                          from the tribe of Levi 12,000,

                                          from the tribe of Issachar 12,000,

                                          8 from the tribe of Zebulun 12,000,

                                          from the tribe of Joseph 12,000,

                                          from the tribe of Benjamin 12,000.

                                          The Great Multitude in White Robes
                                          9 After this I looked, and there before me was a great multitude that no one could count, from every nation, tribe, people and language, standing before the throne and before the Lamb. They were wearing white robes and were holding palm branches in their hands. 10 And they cried out in a loud voice:

                                          “Salvation belongs to our God,
                                          who sits on the throne,
                                          and to the Lamb.”

                                          11 All the angels were standing around the throne and around the elders and the four living creatures. They fell down on their faces before the throne and worshiped God, 12 saying:

                                          “Amen!
                                          Praise and glory
                                          and wisdom and thanks and honor
                                          and power and strength
                                          be to our God for ever and ever.
                                          Amen!”

                                          13 Then one of the elders asked me, “These in white robes—who are they, and where did they come from?”

                                          14 I answered, “Sir, you know.”

                                          And he said, “These are they who have come out of the great tribulation; they have washed their robes and made them white in the blood of the Lamb. 15 Therefore,

                                          “they are before the throne of God
                                              and serve him day and night in his temple;
                                          and he who sits on the throne
                                              will shelter them with his presence.
                                          16 ‘Never again will they hunger;
                                              never again will they thirst.
                                          The sun will not beat down on them,’[a]
                                              nor any scorching heat.
                                          17 For the Lamb at the center of the throne
                                              will be their shepherd;
                                          ‘he will lead them to springs of living water.’[b]
                                              ‘And God will wipe away every tear from their eyes.’[c]”  
                                                                                    </p>
                                                                           </div>
                                    <div className={styles.card}>

                                        <h2 className={styles.chapter}>The Revelation Chpt VII </h2>
                                        <p>

                                        The Seventh Seal and the Golden Censer
                                        8 When he opened the seventh seal, there was silence in heaven for about half an hour.

                                        2 And I saw the seven angels who stand before God, and seven trumpets were given to them.

                                        3 Another angel, who had a golden censer, came and stood at the altar. He was given much incense to offer, with the prayers of all God’s people, on the golden altar in front of the throne. 4 The smoke of the incense, together with the prayers of God’s people, went up before God from the angel’s hand. 5 Then the angel took the censer, filled it with fire from the altar, and hurled it on the earth; and there came peals of thunder, rumblings, flashes of lightning and an earthquake.

                                        The Trumpets
                                        6 Then the seven angels who had the seven trumpets prepared to sound them.

                                        7 The first angel sounded his trumpet, and there came hail and fire mixed with blood, and it was hurled down on the earth. A third of the earth was burned up, a third of the trees were burned up, and all the green grass was burned up.

                                        8 The second angel sounded his trumpet, and something like a huge mountain, all ablaze, was thrown into the sea. A third of the sea turned into blood, 9 a third of the living creatures in the sea died, and a third of the ships were destroyed.

                                        10 The third angel sounded his trumpet, and a great star, blazing like a torch, fell from the sky on a third of the rivers and on the springs of water— 11 the name of the star is Wormwood.[a] A third of the waters turned bitter, and many people died from the waters that had become bitter.

                                        12 The fourth angel sounded his trumpet, and a third of the sun was struck, a third of the moon, and a third of the stars, so that a third of them turned dark. A third of the day was without light, and also a third of the night.

                                        13 As I watched, I heard an eagle that was flying in midair call out in a loud voice: “Woe! Woe! Woe to the inhabitants of the earth, because of the trumpet blasts about to be sounded by the other three angels!”
 
                                        </p>
                                  </div>




                                <div className={styles.card}>

                                        <h2 className={styles.chapter}>The Revelation Chpt IX</h2>
                                        <p>
                                          9 The fifth angel sounded his trumpet, and I saw a star that had fallen from the sky to the earth. The star was given the key to the shaft of the Abyss. 2 When he opened the Abyss, smoke rose from it like the smoke from a gigantic furnace. The sun and sky were darkened by the smoke from the Abyss. 3 And out of the smoke locusts came down on the earth and were given power like that of scorpions of the earth. 4 They were told not to harm the grass of the earth or any plant or tree, but only those people who did not have the seal of God on their foreheads. 5 They were not allowed to kill them but only to torture them for five months. And the agony they suffered was like that of the sting of a scorpion when it strikes. 6 During those days people will seek death but will not find it; they will long to die, but death will elude them.

                                              7 The locusts looked like horses prepared for battle. On their heads they wore something like crowns of gold, and their faces resembled human faces. 8 Their hair was like women’s hair, and their teeth were like lions’ teeth. 9 They had breastplates like breastplates of iron, and the sound of their wings was like the thundering of many horses and chariots rushing into battle. 10 They had tails with stingers, like scorpions, and in their tails they had power to torment people for five months. 11 They had as king over them the angel of the Abyss, whose name in Hebrew is Abaddon and in Greek is Apollyon (that is, Destroyer).

                                              12 The first woe is past; two other woes are yet to come.

                                              13 The sixth angel sounded his trumpet, and I heard a voice coming from the four horns of the golden altar that is before God. 14 It said to the sixth angel who had the trumpet, “Release the four angels who are bound at the great river Euphrates.” 15 And the four angels who had been kept ready for this very hour and day and month and year were released to kill a third of mankind. 16 The number of the mounted troops was twice ten thousand times ten thousand. I heard their number.

                                              17 The horses and riders I saw in my vision looked like this: Their breastplates were fiery red, dark blue, and yellow as sulfur. The heads of the horses resembled the heads of lions, and out of their mouths came fire, smoke and sulfur. 18 A third of mankind was killed by the three plagues of fire, smoke and sulfur that came out of their mouths. 19 The power of the horses was in their mouths and in their tails; for their tails were like snakes, having heads with which they inflict injury.

                                              20 The rest of mankind who were not killed by these plagues still did not repent of the work of their hands; they did not stop worshiping demons, and idols of gold, silver, bronze, stone and wood—idols that cannot see or hear or walk. 21 Nor did they repent of their murders, their magic arts, their sexual immorality or their thefts.
                                          
                                        </p>
                                  </div>
                                  


                      </div>
                </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
