import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      
       
       
        <div className={styles.hero}>
           <h2 className={styles.holy}>THE WORD</h2>
                <h1 className={styles.bible}>
                    <a href="https://the-holy-bible.vercel.app/" target="_blank">OF GOD</a>
                </h1>
        
        <h1 className={styles.title}>
          THE REVELATION
        </h1>
         <div  className={styles.image}>
       <Image 
                                src="/blue_letter_bible.jpeg"
                                alt="Jesus teaching"
                                height={900}
                                width={2000}
                                priority
                              />
          </div>
                      <div className={styles.nav}>           
      <a href="https://colossians.vercel.app/">
             <Image 
                                src="/chevron-left.svg"
                                alt="left"
                                 height={25}
                                width={25}
                                priority
                              />
       </a>

         <a href="#PayPalButton">
            <Image 
                                src="/chevron-down.svg"
                                alt="down"
                                 height={25}
                                width={25}
                                priority
                              />
           
        </a> 
         <a href="https://second-thessalonians.vercel.app/">
           <Image 
                                src="/chevron-right.svg"
                                alt="right"
                                 height={25}
                                width={25}
                                priority
                              />
           
        </a> 
         
               </div>
                <div className={styles.iframe}>
                      <iframe width="100%" height="315" src="https://www.youtube.com/embed/5nvVVcYD-0w" title="YouTube video player" frameborder="1" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
                </div>        
      <div className={styles.grid}>
          <div className={styles.card}>
            <h2 className={styles.chapter}>The Revelation Chpt I</h2>
            <p>
              The revelation from Jesus Christ, which God gave him to show his servants what must soon take place. He made it known by sending his angel to his servant John, 2 who testifies to everything he saw—that is, the word of God and the testimony of Jesus Christ. 3 
Blessed is the one who reads aloud the words of this prophecy, and blessed are those who hear it and take to heart what is written in it, because the time is near.

Greetings and Doxology
4 John,

To the seven churches in the province of Asia:

Grace and peace to you from him who is, and who was, and who is to come, and from the seven spirits[a] before his throne, 5 and from Jesus Christ, who is the faithful witness, the firstborn from the dead, and the ruler of the kings of the earth.

To him who loves us and has freed us from our sins by his blood, 6 and has made us to be a kingdom and priests to serve his God and Father—to him be glory and power for ever and ever! Amen.

7 “Look, he is coming with the clouds,”[b]
    and “every eye will see him,
even those who pierced him”;
    and all peoples on earth “will mourn because of him.”[c]
So shall it be! Amen.

8 “I am the Alpha and the Omega,” says the Lord God, “who is, and who was, and who is to come, the Almighty.”

John’s Vision of Christ
9 I, John, your brother and companion in the suffering and kingdom and patient endurance that are ours in Jesus, was on the island of Patmos because of the word of God and the testimony of Jesus. 10 On the Lord’s Day I was in the Spirit, and I heard behind me a loud voice like a trumpet, 11 which said: “Write on a scroll what you see and send it to the seven churches: to Ephesus, Smyrna, Pergamum, Thyatira, Sardis, Philadelphia and Laodicea.”

12 I turned around to see the voice that was speaking to me. And when I turned I saw seven golden lampstands, 13 and among the lampstands was someone like a son of man,[d] dressed in a robe reaching down to his feet and with a golden sash around his chest. 14 The hair on his head was white like wool, as white as snow, and his eyes were like blazing fire. 15 His feet were like bronze glowing in a furnace, and his voice was like the sound of rushing waters. 16 In his right hand he held seven stars, and coming out of his mouth was a sharp, double-edged sword. His face was like the sun shining in all its brilliance.

17 When I saw him, I fell at his feet as though dead. Then he placed his right hand on me and said: “Do not be afraid. I am the First and the Last. 18 I am the Living One; I was dead, and now look, I am alive for ever and ever! And I hold the keys of death and Hades.

19 “Write, therefore, what you have seen, what is now and what will take place later. 20 The mystery of the seven stars that you saw in my right hand and of the seven golden lampstands is this: The seven stars are the angels[e] of the seven churches, and the seven lampstands are the seven churches.
              </p>
              </div>

          <div className={styles.card}>
           <h2 className={styles.chapter}>The Revelation Chpt II</h2>
            <p>To the Church in Ephesus
2 “To the angel[a] of the church in Ephesus write:

These are the words of him who holds the seven stars in his right hand and walks among the seven golden lampstands. 2 I know your deeds, your hard work and your perseverance. I know that you cannot tolerate wicked people, that you have tested those who claim to be apostles but are not, and have found them false. 3 You have persevered and have endured hardships for my name, and have not grown weary.

4 Yet I hold this against you: You have forsaken the love you had at first. 5 Consider how far you have fallen! Repent and do the things you did at first. If you do not repent, I will come to you and remove your lampstand from its place. 6 But you have this in your favor: You hate the practices of the Nicolaitans, which I also hate.

7 Whoever has ears, let them hear what the Spirit says to the churches. To the one who is victorious, I will give the right to eat from the tree of life, which is in the paradise of God.

To the Church in Smyrna
8 “To the angel of the church in Smyrna write:

These are the words of him who is the First and the Last, who died and came to life again. 9 I know your afflictions and your poverty—yet you are rich! I know about the slander of those who say they are Jews and are not, but are a synagogue of Satan. 10 Do not be afraid of what you are about to suffer. I tell you, the devil will put some of you in prison to test you, and you will suffer persecution for ten days. Be faithful, even to the point of death, and I will give you life as your victor’s crown.

11 Whoever has ears, let them hear what the Spirit says to the churches. The one who is victorious will not be hurt at all by the second death.

To the Church in Pergamum
12 “To the angel of the church in Pergamum write:

These are the words of him who has the sharp, double-edged sword. 13 I know where you live—where Satan has his throne. Yet you remain true to my name. You did not renounce your faith in me, not even in the days of Antipas, my faithful witness, who was put to death in your city—where Satan lives.

14 Nevertheless, I have a few things against you: There are some among you who hold to the teaching of Balaam, who taught Balak to entice the Israelites to sin so that they ate food sacrificed to idols and committed sexual immorality. 15 Likewise, you also have those who hold to the teaching of the Nicolaitans. 16 Repent therefore! Otherwise, I will soon come to you and will fight against them with the sword of my mouth.

17 Whoever has ears, let them hear what the Spirit says to the churches. To the one who is victorious, I will give some of the hidden manna. I will also give that person a white stone with a new name written on it, known only to the one who receives it.

To the Church in Thyatira
18 “To the angel of the church in Thyatira write:

These are the words of the Son of God, whose eyes are like blazing fire and whose feet are like burnished bronze. 19 I know your deeds, your love and faith, your service and perseverance, and that you are now doing more than you did at first.

20 Nevertheless, I have this against you: You tolerate that woman Jezebel, who calls herself a prophet. By her teaching she misleads my servants into sexual immorality and the eating of food sacrificed to idols. 21 I have given her time to repent of her immorality, but she is unwilling. 22 So I will cast her on a bed of suffering, and I will make those who commit adultery with her suffer intensely, unless they repent of her ways. 23 I will strike her children dead. Then all the churches will know that I am he who searches hearts and minds, and I will repay each of you according to your deeds.

24 Now I say to the rest of you in Thyatira, to you who do not hold to her teaching and have not learned Satan’s so-called deep secrets, ‘I will not impose any other burden on you, 25 except to hold on to what you have until I come.’

26 To the one who is victorious and does my will to the end, I will give authority over the nations— 27 that one ‘will rule them with an iron scepter and will dash them to pieces like pottery’[b]—just as I have received authority from my Father. 28 I will also give that one the morning star. 29 Whoever has ears, let them hear what the Spirit says to the churches.</p>
          </div>

          <div
            className={styles.card}
          >
           <h2 className={styles.chapter}>The Revelation Chpt III</h2>
            <p>
            To the Church in Sardis
3 “To the angel[a] of the church in Sardis write:

These are the words of him who holds the seven spirits[b] of God and the seven stars. I know your deeds; you have a reputation of being alive, but you are dead. 2 Wake up! Strengthen what remains and is about to die, for I have found your deeds unfinished in the sight of my God. 3 Remember, therefore, what you have received and heard; hold it fast, and repent. But if you do not wake up, I will come like a thief, and you will not know at what time I will come to you.

4 Yet you have a few people in Sardis who have not soiled their clothes. They will walk with me, dressed in white, for they are worthy. 5 The one who is victorious will, like them, be dressed in white. I will never blot out the name of that person from the book of life, but will acknowledge that name before my Father and his angels. 6 Whoever has ears, let them hear what the Spirit says to the churches.

To the Church in Philadelphia
7 “To the angel of the church in Philadelphia write:

These are the words of him who is holy and true, who holds the key of David. What he opens no one can shut, and what he shuts no one can open. 8 I know your deeds. See, I have placed before you an open door that no one can shut. I know that you have little strength, yet you have kept my word and have not denied my name. 9 I will make those who are of the synagogue of Satan, who claim to be Jews though they are not, but are liars—I will make them come and fall down at your feet and acknowledge that I have loved you. 10 Since you have kept my command to endure patiently, I will also keep you from the hour of trial that is going to come on the whole world to test the inhabitants of the earth.

11 I am coming soon. Hold on to what you have, so that no one will take your crown. 12 The one who is victorious I will make a pillar in the temple of my God. Never again will they leave it. I will write on them the name of my God and the name of the city of my God, the new Jerusalem, which is coming down out of heaven from my God; and I will also write on them my new name. 13 Whoever has ears, let them hear what the Spirit says to the churches.

To the Church in Laodicea
14 “To the angel of the church in Laodicea write:

These are the words of the Amen, the faithful and true witness, the ruler of God’s creation. 15 I know your deeds, that you are neither cold nor hot. I wish you were either one or the other! 16 So, because you are lukewarm—neither hot nor cold—I am about to spit you out of my mouth. 17 You say, ‘I am rich; I have acquired wealth and do not need a thing.’ But you do not realize that you are wretched, pitiful, poor, blind and naked. 18 I counsel you to buy from me gold refined in the fire, so you can become rich; and white clothes to wear, so you can cover your shameful nakedness; and salve to put on your eyes, so you can see.

19 Those whom I love I rebuke and discipline. So be earnest and repent. 20 Here I am! I stand at the door and knock. If anyone hears my voice and opens the door, I will come in and eat with that person, and they with me.

21 To the one who is victorious, I will give the right to sit with me on my throne, just as I was victorious and sat down with my Father on his throne. 22 Whoever has ears, let them hear what the Spirit says to the churches.”
            </p>
          </div>
<div className={styles.card}>

<h2 className={styles.chapter}>The Revelation Chpt IV</h2>
<p>
The Throne in Heaven
4 After this I looked, and there before me was a door standing open in heaven. And the voice I had first heard speaking to me like a trumpet said, “Come up here, and I will show you what must take place after this.” 2 At once I was in the Spirit, and there before me was a throne in heaven with someone sitting on it. 3 And the one who sat there had the appearance of jasper and ruby. A rainbow that shone like an emerald encircled the throne. 4 Surrounding the throne were twenty-four other thrones, and seated on them were twenty-four elders. They were dressed in white and had crowns of gold on their heads. 5 From the throne came flashes of lightning, rumblings and peals of thunder. In front of the throne, seven lamps were blazing. These are the seven spirits[a] of God. 6 Also in front of the throne there was what looked like a sea of glass, clear as crystal.

In the center, around the throne, were four living creatures, and they were covered with eyes, in front and in back. 7 The first living creature was like a lion, the second was like an ox, the third had a face like a man, the fourth was like a flying eagle. 8 Each of the four living creatures had six wings and was covered with eyes all around, even under its wings. Day and night they never stop saying:

“‘Holy, holy, holy

is the Lord God Almighty,’[b]

who was, and is, and is to come.”

9 Whenever the living creatures give glory, honor and thanks to him who sits on the throne and who lives for ever and ever, 10 the twenty-four elders fall down before him who sits on the throne and worship him who lives for ever and ever. They lay their crowns before the throne and say:

11 “You are worthy, our Lord and God,
    to receive glory and honor and power,
for you created all things,
    and by your will they were created
    and have their being.”
</p>
</div>

        </div>
</div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
